PetCafe(Remake)/Controllers/DogController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PetCafe_Remake_.Extension;
using PetCafe_Remake_.Interface;
using PetCafe_Remake_.Models;
using PetCafe_Remake_.ViewModels;

namespace PetCafe_Remake_.Controllers
{
    public class DogController : Controller
    {
        private readonly IDogRepository _dogRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DogController(IDogRepository dogRepository, IPhotoService photoService,
            IHttpContextAccessor httpContextAccessor)
        {
            _dogRepository = dogRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            //bring in <dog> so that can @model in cshtml
            IEnumerable<Dog> dogs = await _dogRepository.GetAll();
            return View(dogs);
        }
        public async Task<IActionResult> Detail(int id)
        {

            Dog dog = await _dogRepository.GetByIdAsync(id);
            return View(dog);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createDogViewModel = new CreateDogViewModel { AppUserId = curUserId };
            return View(createDogViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Create(CreateDogViewModel dogVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(dogVM.Image);
                var dog = new Dog
                {
                    DogName = dogVM.DogName,
                    Introduction = dogVM.Introduction,
                    Image = result.Url.ToString(),
                    AppUserId = dogVM.AppUserId,
                    VisitTime = new VisitTime
                    {
                        Day = dogVM.VisitTime.Day,
                        TimeFrame = dogVM.VisitTime.TimeFrame

                    }
                };
                _dogRepository.Add(dog);
                return RedirectToAction("index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(dogVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) //to copy message as a form data
        {
            var dog = await _dogRepository.GetByIdAsync(id);
            if (dog == null) return View("Error");
            var dogVM = new EditDogViewModel
            {
                DogName = dog.DogName,
                Introduction = dog.Introduction,
                VisitTimeId = dog.VisitTimeId,
                VisitTime = dog.VisitTime,
                URL = dog.Image,
                DogCategory = dog.DogCategory,

            };
            return View(dogVM);
        }

        [HttpPost] //to update
        public async Task<IActionResult> Edit(int id, EditDogViewModel dogVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(" ", "Failed to edit club");
                return View("Edit", dogVM);
            }

            var dogId = await _dogRepository.GetByIdAsyncNoTracking(id);

            if(dogId != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(dogId.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(dogVM);
                }

            var photoResult = await _photoService.AddPhotoAsync(dogVM.Image);
            if (photoResult.Error != null)
            {
                ModelState.AddModelError("Image", "Photo upload failed");
                return View(dogVM);
            }
            var dog = new Dog //no need to put foreign inside
                {
                    Id = id,
                    DogName = dogVM.DogName,
                    Introduction = dogVM.Introduction,
                    Image = photoResult.Url.ToString(),
                    VisitTimeId = dogVM.VisitTimeId,
                    VisitTime = dogVM.VisitTime,
                    AppUserId = dogId.AppUserId
            };
            _dogRepository.Update(dog);
            return RedirectToAction("index");
            }
            else
            {
                return View(dogVM); 
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var dogDetails = await _dogRepository.GetByIdAsync(id);
            if (dogDetails == null) return View("Error");
            return View(dogDetails);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteDog(int id)
        {
            var dogDetails = await _dogRepository.GetByIdAsync(id);
            if (dogDetails == null) return View("Error");
            _dogRepository.Delete(dogDetails);
            return RedirectToAction("Index");
        }
    }
}

PetCafe(Remake)/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using PetCafe_Remake_.Extension;
using PetCafe_Remake_.Interface;
using PetCafe_Remake_.Models;
using PetCafe_Remake_.ViewModels;

namespace PetCafe_Remake_.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public EventController(IEventRepository eventRepository, IPhotoService photoService,
            IHttpContextAccessor httpContextAccessor)
        {
            _eventRepository = eventRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Event> events = await _eventRepository.GetAll();
            return View(events);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Event _event = await _eventRepository.GetByIdAsync(id);
            return View(_event);
        }
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createEventViewModel = new CreateEventViewModel { AppUserId = curUserId };
            return View(createEventViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEventViewModel eventVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(eventVM.Image);
                var _event = new Event
                {
                    EventName = eventVM.EventName,
                    Introduction = eventVM.Introduction,
                    Image = result.Url.ToString(),
                    EventTime = eventVM.EventTime,
                    Region = eventVM.Region,
                    AppUserId = eventVM.AppUserId

                };
                _eventRepository.Add(_event);
                return RedirectToAction("index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(eventVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) //to copy message as a form data
        {
            var _event = await _eventRepository.GetByIdAsync(id);
            if (_event == null) return View("Error");
            var _eventVM = new EditEventViewModel
            {
                EventName = _event.EventName,
                Introduction = _event.Introduction,
                EventTime = _event.EventTime,
                URL = _event.Image,
                EventCategory = _event.EventCategory,
                Region = _event.Region

            };
            return View(_eventVM);
        }
        [HttpPost] //to update
        public async Task<IActionResult> Edit(int id, EditEventViewModel eventVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(" ", "Failed to edit club");
                return View("Edit", eventVM);
            }

            var eventId = await _eventRepository.GetByIdAsyncNoTracking(id);

            if (eventId != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(eventId.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(eventVM);
                }

                var photoResult = await _photoService.AddPhotoAsync(eventVM.Image);
                if (photoResult.Error != null)
                {
                    ModelState.AddModelError("Image", "Photo upload failed");
                    return View(eventVM);
                }
                var _event = new Event //no need to put foreign inside
                {
                    Id = id,
                    EventName = eventVM.EventName,
                    EventCategory = eventVM.EventCategory,
                    Introduction = eventVM.Introduction,
                    Image = photoResult.Url.ToString(),
                    EventTime = (DateTime)eventVM.EventTime,
                    AppUserId = eventId.AppUserId,
                    Region = eventVM.Region
                };
                _eventRepository.Update(_event);
                return RedirectToAction("index");
            }
            else
            {
                return View(eventVM);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var eventDetails = await _eventRepository.GetByIdAsync(id);
            if (eventDetails == null) return View("Error");
            return View(eventDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteEvent(int id)
        {
            var eventDetails = await _eventRepository.GetByIdAsync(id);
            if (eventDetails == null) return View("Error");
            _eventRepository.Delete(eventDetails);
            return RedirectToAction("Index");
        }


    }
}

PetCafe(Remake)/Controllers/MemberController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PetCafe_Remake_.Extension;
using PetCafe_Remake_.Interface;
using PetCafe_Remake_.Models;
using PetCafe_Remake_.ViewModels;

namespace PetCafe_Remake_.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberRepository _memberRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<AppUser> _userManager;

        public MemberController(IMemberRepository memberRepository, IPhotoService photoService,
            IHttpContextAccessor httpContextAccessor, UserManager<AppUser> userManager)
        {
            _memberRepository = memberRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userEvents = await _memberRepository.GetAllUserEvents();
            var userDogs = await _memberRepository.GetAllUserDogs();
            var memberViewModel = new MemberViewModel()
            {
                Events = userEvents,
                Dogs = userDogs,
            };
            return View(memberViewModel);

        }

        public async Task<IActionResult> EditProfile()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return View("Error");
            }
            var editUserViewModel = new EditProfileViewModel()
            {
                Gender = user.Gender,
                ProfileImageUrl = user.ProfileImageUrl,
                Occupation = user.Occupation,
                Region = user.Region,
                AboutMe = user.AboutMe,


            };
            return View(editUserViewModel);
        }

        //receive form
        [HttpPost]
        public async Task<IActionResult> EditProfile(EditProfileViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditProfile", editVM);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return View("Error");
            }

            if (editVM.Image != null) // only update profile image
            {
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                if (photoResult.Error != null)
                {
                    ModelState.AddModelError("Image", "Failed to upload image");
                    return View("EditProfile", editVM);
                }

                if (!string.IsNullOrEmpty(user.ProfileImageUrl))
                {
                    _ = _photoService.DeletePhotoAsync(user.ProfileImageUrl);
                }

                user.ProfileImageUrl = photoResult.Url.ToString();
                editVM.ProfileImageUrl = user.ProfileImageUrl;

                await _userManager.UpdateAsync(user);

                return View(editVM);
            }
            user.Gender = editVM.Gender;
            user.Region = editVM.Region;
            user.UserName = editVM.UserName;
            user.Occupation = editVM.Occupation;
            user.AboutMe = editVM.AboutMe;
            await _userManager.UpdateAsync(user);

            return RedirectToAction("Detail", "User", new { user.Id });
        }



    }
}

PetCafe(Remake)/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Not a coffee shop only</title>

    
  <!-- Favicons -->
  <link href="~/img/favicon.png" rel="icon">
  <link href="~/mg/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/lib/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/lib/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="~/lib/remixicon/remixicon.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/css/style.css" rel="stylesheet">
 <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <!-- =======================================================
  * Template Name: MeFamily - v4.7.0
  * Template URL: https://bootstrapmade.com/family-multipurpose-html-bootstrap-template-free/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

  </head>
  <body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">
      <h1 class="logo"><a asp-area="" asp-controller="Home" asp-action="Index">Dofe</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      <nav id="navbar" class="navbar fix-top">
        <ul>
          <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
         @if (SignInManager.IsSignedIn(User))
         {
         <li><a asp-area="" asp-controller="User" asp-action="Index">UserPage</a></li>
         }
          <li><a asp-area="" asp-controller="Dog" asp-action="Index">Dogs</a></li>
          <li><a asp-area="" asp-controller="Event" asp-action="Index">Events</a></li>
         @if (SignInManager.IsSignedIn(User))
         {
          <li><a asp-area="" asp-controller="Member" asp-action="Index">Member</a></li>
          <li><a asp-area="" asp-controller="Account" asp-action="Logout" class="nav-link text-dark">Logout</a></li>
         }
         else
         {
          <li><a asp-area="" asp-controller="Account" asp-action="Register" class="nav-link text-dark">Register</a></li>
          <li><a asp-area="" asp-controller="Account" asp-action="Login" class="nav-link text-dark">Login</a></li>
          }
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  <footer id="footer">
    <div class="container">
      <h3>Dofe</h3>
      <p>Bootstrap template from MeFamily</p>
      <p>Photos from Pixabay.com</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>MeFamily</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/family-multipurpose-html-bootstrap-template-free/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/lib/glightbox/js/glightbox.min.js"></script>
  <script src="~/lib/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="~/lib/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/js/main.js"></script>
  </body>
    @await RenderSectionAsync("Scripts", required: false)
</html>